### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by bedletskyi** [bedletskyi/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by rasamashka** [comment]
- Hi, my name is Vitaly – I am a future software developer. Yesterday I just learned how to create a Hello World application in Java, and today I have already passed the first level in Binary Studio Academy. I'm making progress, but I still have a lot to learn, and I won't stop there…
