### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by bedletskyi** [bedletskyi/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by rasamashka** [comment]
https://github.com/bedletskyi
https://www.facebook.com/profile.php?id=100001768810254
bedletskyi@gmail.com
Skype: bedletskyi
Telegram: @bedletskyi
