### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by bedletskyi** [bedletskyi/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by rasamashka** [comment]
**LANGUAGES**
Українська, Русский, English, Français

**SKILLS**
Java, Spring Boot, Lombok, Maven, MySQL, GIT, JavaScript, Vue.js, HTML, CSS, Sass, Bootstrap, Microsoft Office, Adobe Photoshop, PHP, Linux, Windows

**CHARACTER**
Pedantic, [Manager](https://www.16personalities.com/ru/lichnost-estj), Sure, Demanding, Сandid, Supervisory

**LIKES😃**
Cinema, TV shows, Rock, Attention to detail, French wines, Mountains, Live music, Nature walks, Architecture

**DISLIKES😞**
Arrogance, Smoking, Russian cinema, Clutter, Bad code, Crowd

**WANTS🥺**
Perform all that I planned, Read books to the end, Be bolder, Travel more
